import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Lsystem from "../components/formula";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  Lsystem(3);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Get started with PMF;</p>
        </div>
        <Canvas>{/* three js data */}</Canvas>
      </main>
    </>
  );
}
